# model/VGG/configs/eval_config.yaml
# 评估配置
evaluation:
  model_path: "model/VGG/vgg16_cifar10_epoch_10.pth"
  batch_size: 128
  device: "cuda"
  save_dir: "model/VGG/results"

# 数据配置
data:
  dataset: "CIFAR10"
  data_dir: "data/cifar10"
  num_workers: 4
  pin_memory: true
  transform:
    - type: "ToTensor"
    - type: "Normalize"
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
