# model/VGG/configs/train_config.yaml
# 模型配置
model:
  name: "VGG16"
  num_classes: 10
  batch_norm: true
  dropout: 0.5

# 训练配置
training:
  batch_size: 128
  learning_rate: 0.01
  momentum: 0.9
  weight_decay: 5e-4
  num_epochs: 10
  device: "cuda" # 或 "cpu"
  save_dir: "model/VGG/checkpoints"
  log_dir: "model/VGG/logs"

# 数据配置
data:
  dataset: "CIFAR10"
  data_dir: "data/cifar10"
  num_workers: 4
  pin_memory: true
  transform:
    train:
      - type: "RandomCrop"
        size: 32
        padding: 4
      - type: "RandomHorizontalFlip"
        p: 0.5
      - type: "ToTensor"
      - type: "Normalize"
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    val:
      - type: "ToTensor"
      - type: "Normalize"
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
